### PR TITLE
Implement the sum and product traits for matrices

### LINKED ISSUE #264: Implement std::iter::Sum
Currently, if I have an iterator of identically sized nalgebra matrices or vectors, I cannot just compute their sum with the sum() member function because that requires std::iter::Sum to be implemented for nalgebra matrices. This means that a less concise fold() must be used instead.

I guess it would probably make sense to implement this trait as a simple loop on top of the existing "+" operator.

### PR DESCRIPTION
**Pull request by brendanzab**
Closes #264

### CODE REVIEW

**Comment by brendanzab** [comment]
I just want to say @sebcrozet, I'm super impressed with how nalgebra is coming along!

**Comment by aepsil0n** [comment]
I could totally merge this, as I was just thinking about the same thing. However, i have barely worked on this library for a long time. So I just want to make sure, that I am not doing anything totally unexpected by merging a PR out of the blue.

@sebcrozet: would you be okay, if I took an active role in maintaining nalgebra again?

**Comment by sebcrozet** [comment]
@aepsil0n : I'm okay with you maintaining nalgebra (including publishing to crates.io) again as long as I approve the non-trivial PRs first (don't hesitate to @-mention me to get my attention on one specific PR that needs approval). I currently have little time to review PRs and publish new releases to crates.io so your help would be greatly appreciated.

This PR seems fine for merging and publishing with a minor version bump. Thanks @brendanzab! (And thanks for the compliment as well!)

**Comment by aepsil0n** [comment]
Great! Then I will do so.

**Comment by sebcrozet** [comment]
@aepsil0n Thanks for merging all those PRs!

**Comment by brendanzab** [comment]
Might need to implement these same traits for other types I realise now... :/

**Pull request merged**
