### PR TITLE
Update rust

### PR DESCRIPTION
**Pull request by retep998**

### CODE REVIEW

**Comment by simnalamburt** [comment]
:+1:

**Comment by bfops** [comment]
+1. Not sure why the CI build is failing.

**Comment by tomaka** [comment]
It's failing because this PR was submitted because the nightly was released.

**Comment by simnalamburt** [comment]
It failed because this PR was made to early

**Comment by retep998** [comment]
Sorry for being such a hipster and making PRs before the nightly is actually available.

**Comment by sebcrozet** [comment]
Still failing on Travis, but for other reasons. Merging.

**Comment by sebcrozet** [comment]
Thanks!

**Pull request merged**
