### PR TITLE
Partial stabilization to Rust 1.0

### PR DESCRIPTION
**Pull request by aepsil0n**
Addresses part of the issues in #108.

### CODE REVIEW

**Comment by aepsil0n** [comment]
This is only failing with the `Arbitrary` feature because of quickcheck. So could be merged nonetheless, since this feature has not been touched afaik.

**Comment by sebcrozet** [comment]
Thanks!

**Comment by tomaka** [comment]
Could one of you upload this? (especially with #106)

**Comment by sebcrozet** [comment]
@tomaka done.

**Comment by tomaka** [comment]
Thanks

**Pull request merged**
