### PR TITLE
Remove phantom data from matrix debug output

### PR DESCRIPTION
**Pull request by aepsil0n**
Addresses #295.

### CODE REVIEW

**Comment by aepsil0n** [comment]
cc @Ralith @Boscop

Does this address your issue appropriately? I also considered the flattened structure and column layout, i.e. `[1, 3, 2, 4]` vs. `[[1, 2], [3, 4]]`. However, this is probably a separate issue not be addressed in this context. And perhaps it is ok like this anyway, as it is closer to a debug view.

**Comment by jswrenn** [comment]
I'd favor a `Debug` that displayed the nalgebra wrapping type. I appreciate that information when I'm using debugging output, and it seems to be a Rust convention; there's even a [`DebugStruct`](https://doc.rust-lang.org/std/fmt/struct.DebugStruct.html) builder API for debugging output that requires the struct name. I'd recommend an implementation like this:
```rust
impl<N: Scalar, R: Dim, C: Dim, S: fmt::Debug> fmt::Debug for Matrix<N, R, C, S> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> Result<(), fmt::Error> {
        fmt.debug_struct(&format!("Matrix<{},{}>", self.rows(), self.cols()))
         .field("data", &self.data)
         .finish()
    }
}
```

or this, if we really want to elide that there's a field called `data`:
```rust
impl<N: Scalar, R: Dim, C: Dim, S: fmt::Debug> fmt::Debug for Matrix<N, R, C, S> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> Result<(), fmt::Error> {
        fmt.debug_tuple(&format!("Matrix<{},{}>", self.rows(), self.cols()))
         .field(&self.data)
         .finish()
    }
}
```

**Comment by Ralith** [comment]
Although I like this as-is, the point about Rust convention is legitimate, so I won't be disappointed if it goes that way instead. It looks like if I really want maximally concise output, I can just format the `data` member directly, since it's public. That's convenient enough for me.

**Comment by jswrenn** [comment]
Does `println!("{:?}", foo.as_slice())` fit your use-case, @Ralith? It reliably prints the data values on a single line, regardless of the backing storage type.

**Comment by Ralith** [comment]
Yep, that would work too.

**Comment by aepsil0n** [comment]
@jswrenn that is a valid concern. I get why it makes sense to clearly distinguish between an plain array and an nalgebra matrix.

What is your reasoning for including the number of rows in columns in your example? After all, our motivation was to reduce noise and that information is not present at the moment and nobody seems to be missing it.

The most conservative change would probably be to simple remove the phantom data part similar to your first suggestion: `Matrix { data: [1, 2, 3, 4] }`. I still have a slight preference for `Matrix([1, 2, 3, 4])`, but given the option so use `as_slice()` instead, I don't care too much either.

**Comment by jswrenn** [comment]
> What is your reasoning for including the number of rows in columns in your example? After all, our motivation was to reduce noise and that information is not present at the moment and nobody seems to be missing it.

Yeah, on second thought, it's a poor addition.

I think the `Debug` output _should_ broadcast that there's a `data` field, since part of the role of the debug output is discoverability--`data` _is_ a public field, and it's one you access in the normal course of using `nalgebra`.

**Comment by aepsil0n** [comment]
Cool, seems like we agree. I'll change the PR accordingly.

**Pull request merged**
